name: build test

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      
      fail-fast: false
      matrix:
        include:
          - os: macos
            target1: x86_64-apple-darwin
            target2: aarch64-apple-darwin
            args: ""
          - os: macos
            target1: aarch64-apple-darwin
            target2: ""
            args: ""

          - os: ubuntu
            target1: x86_64-unknown-linux-gnu
            target2: ""
            args: ""
          - os: ubuntu
            target1: aarch64-unknown-linux-gnu
            target2: x86_64-unknown-linux-gnu
            args: ""

          - os: windows
            target1: x86_64-pc-windows-msvc
            target2: ""
            args: "-b"
          - os: windows
            target1: aarch64-pc-windows-msvc
            target2: x86_64-pc-windows-msvc
            args: "-b"
            
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: setup node
        uses: oven-sh/setup-bun@v2

        
      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf libsoup2.4-dev libjavascriptcoregtk-4.0-dev

      - name: checkout
        uses: actions/checkout@v4
      
      - name: installation modules nodejs
        run: bun install

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target1 }},${{ matrix.target2 }}

      - name: test build
        run: bun run build

      - name: test tauri build
        run: |
            cd src-tauri
            cargo build --target ${{ matrix.target1 }} ${{ matrix.args }}