name: build test
on:
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
      
    strategy:
      
      fail-fast: false
      matrix:
        include:
          - os: macos
            target: x86_64-apple-darwin
            args: ""
          - os: macos
            target: aarch64-apple-darwin
            args: ""

          - os: ubuntu
            target: x86_64-unknown-linux-gnu
            args: ""
          - os: ubuntu
            target: aarch64-unknown-linux-gnu
            args: ""

          - os: windows
            target: x86_64-pc-windows-msvc
            args: ""

          - os: windows
            target: aarch64-pc-windows-msvc
            args: ""

            
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: ${{ matrix.target }}
            components: rustfmt, clippy

      - name: install dependencies (ubuntu only)
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y libsoup-3.0-0 libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
        
      - name: installation modules nodejs
        run: npm install

      - name: test build
        run: npm run build

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        working-directory: ./src-tauri
        with:
          use-cross: true
          command: check
          args: --target ${{ matrix.target }}

      - name: test tauri build
        run: |
            cd src-tauri
            cargo build --target ${{ matrix.target }} ${{ matrix.args }}